### ISSUE TITLE
bootstrap4 scaffolding?

### ISSUE THREAD

**Issue by JohnA3** [jolicode/generator-joli-symfony#16]
Hi

Any chance for adding Bootstrap4 to generator's install options?

I realize it's "alpha" still, but it's definitely on-the-way.  Would be nice to be able to bring up a test environment with it.

Thanks!

**Comment by lbrunet** [comment]
Hi, 

Only Stable versions are handled on the generator.

You can install Bootstrap4 in the project with `bower`

`$ bower install https://github.com/twbs/bootstrap/tree/v4.0.0-alpha --save`

Thanks !
