### ISSUE TITLE
install error "UNMET PEER DEPENDENCY yo@>=1.0.0", but yo --version == 1.4.8 ?

### ISSUE THREAD

**Issue by JohnA3** [jolicode/generator-joli-symfony#17]
I'm trying to install the generator.  The install fails to find existing 'yo'.

    node -v
        v4.1.2
    npm -v
        3.3.7
    npm i -g yo
    which yo
        /usr/bin/yo
    yo --version
        1.4.8

    npm i -g generator-joli-symfony
        npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
        npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
        ...
        /usr/lib
        ├─┬ generator-joli-symfony@1.0.0 
        │ ├─┬ chalk@0.5.1 
        │ │ ├── ansi-styles@1.1.0 
        │ │ ├── escape-string-regexp@1.0.3 
        │ │ ├── has-ansi@0.1.0 
        │ │ ├── strip-ansi@0.3.0 
        │ │ └── supports-color@0.2.0 
        │ ├─┬ fs-extra@0.22.1 
        │ │ ├── graceful-fs@4.1.2 
        │ │ └── jsonfile@2.2.2 
        │ ├─┬ js-yaml@3.4.3 
        │ │ ├─┬ argparse@1.0.2 
        │ │ │ ├── lodash@3.10.1 
        │ │ │ └── sprintf-js@1.0.3 
        │ │ └── esprima@2.6.0 
        │ ├─┬ rimraf@2.4.3 
        │ │ └─┬ glob@5.0.15 
        │ │   ├─┬ inflight@1.0.4 
        │ │   │ └── wrappy@1.0.1 
        │ │   ├── inherits@2.0.1 
        │ │   ├─┬ minimatch@3.0.0 
        │ │   │ └─┬ brace-expansion@1.1.1 
        │ │   │   ├── balanced-match@0.2.0 
        │ │   │   └── concat-map@0.0.1 
        │ │   ├── once@1.3.2 
        │ │   └── path-is-absolute@1.0.0 
        │ ├─┬ yeoman-generator@0.18.10 
        │ │ ├── async@0.9.2 
        │ │ ├─┬ chalk@1.1.1 
        │ │ │ ├── ansi-styles@2.1.0 
        │ │ │ ├─┬ has-ansi@2.0.0 
        │ │ │ │ └── ansi-regex@2.0.0 
        │ │ │ ├── strip-ansi@3.0.0 
        │ │ │ └── supports-color@2.0.0 
        │ │ ├─┬ cheerio@0.18.0 
        │ │ │ ├─┬ CSSselect@0.4.1 
        │ │ │ │ ├── CSSwhat@0.4.7 
        │ │ │ │ └── domutils@1.4.3 
        │ │ │ ├─┬ dom-serializer@0.0.1 
        │ │ │ │ └── domelementtype@1.1.3 
        │ │ │ ├── entities@1.1.1 
        │ │ │ ├─┬ htmlparser2@3.8.3 
        │ │ │ │ ├── domelementtype@1.3.0 
        │ │ │ │ ├── domhandler@2.3.0 
        │ │ │ │ ├── domutils@1.5.1 
        │ │ │ │ ├── entities@1.0.0 
        │ │ │ │ └── readable-stream@1.1.13 
        │ │ │ └── lodash@2.4.2 
        │ │ ├─┬ class-extend@0.1.1 
        │ │ │ └── lodash@2.4.2 
        │ │ ├─┬ cli-table@0.3.1 
        │ │ │ └── colors@1.0.3 
        │ │ ├─┬ cross-spawn@0.2.9 
        │ │ │ └── lru-cache@2.7.0 
        │ │ ├── dargs@3.0.1 
        │ │ ├─┬ dateformat@1.0.11 
        │ │ │ ├── get-stdin@5.0.0 
        │ │ │ └─┬ meow@3.4.2 
        │ │ │   ├─┬ camelcase-keys@1.0.0 
        │ │ │   │ ├── camelcase@1.2.1 
        │ │ │   │ └── map-obj@1.0.1 
        │ │ │   ├── loud-rejection@1.0.0 
        │ │ │   ├── minimist@1.2.0 
        │ │ │   ├─┬ normalize-package-data@2.3.4 
        │ │ │   │ ├── hosted-git-info@2.1.4 
        │ │ │   │ ├─┬ is-builtin-module@1.0.0 
        │ │ │   │ │ └── builtin-modules@1.1.0 
        │ │ │   │ ├── semver@5.0.3 
        │ │ │   │ └─┬ validate-npm-package-license@3.0.1 
        │ │ │   │   ├─┬ spdx-correct@1.0.1 
        │ │ │   │   │ └── spdx-license-ids@1.0.2 
        │ │ │   │   └─┬ spdx-expression-parse@1.0.0 
        │ │ │   │     └── spdx-exceptions@1.0.3 
        │ │ │   ├── object-assign@4.0.1 
        │ │ │   ├─┬ read-pkg-up@1.0.1 
        │ │ │   │ ├─┬ find-up@1.0.0 
        │ │ │   │ │ ├── path-exists@2.0.0 
        │ │ │   │ │ └─┬ pinkie-promise@1.0.0 
        │ │ │   │ │   └── pinkie@1.0.0 
        │ │ │   │ └─┬ read-pkg@1.1.0 
        │ │ │   │   ├─┬ load-json-file@1.0.1 
        │ │ │   │   │ ├─┬ parse-json@2.2.0 
        │ │ │   │   │ │ └── error-ex@1.2.0 
        │ │ │   │   │ └── pify@2.2.0 
        │ │ │   │   └── path-type@1.0.0 
        │ │ │   ├─┬ redent@1.0.0 
        │ │ │   │ ├─┬ indent-string@2.1.0 
        │ │ │   │ │ └── repeating@2.0.0 
        │ │ │   │ └─┬ strip-indent@1.0.1 
        │ │ │   │   └── get-stdin@4.0.1 
        │ │ │   └── trim-newlines@1.0.0 
        │ │ ├─┬ debug@2.2.0 
        │ │ │ └── ms@0.7.1 
        │ │ ├── detect-conflict@1.0.0 
        │ │ ├── diff@1.4.0 
        │ │ ├─┬ download@3.3.0 
        │ │ │ ├─┬ concat-stream@1.5.0 
        │ │ │ │ ├─┬ readable-stream@2.0.2 
        │ │ │ │ │ ├── process-nextick-args@1.0.3 
        │ │ │ │ │ └── util-deprecate@1.0.2 
        │ │ │ │ └── typedarray@0.0.6 
        │ │ │ ├─┬ decompress-tar@2.0.2 
        │ │ │ │ ├── is-tar@1.0.0 
        │ │ │ │ ├─┬ strip-dirs@0.1.1 
        │ │ │ │ │ ├── get-stdin@3.0.2 
        │ │ │ │ │ ├─┬ is-absolute@0.1.7 
        │ │ │ │ │ │ └── is-relative@0.1.3 
        │ │ │ │ │ └─┬ is-integer@1.0.6 
        │ │ │ │ │   └─┬ is-finite@1.0.1 
        │ │ │ │ │     └── number-is-nan@1.0.0 
        │ │ │ │ └─┬ tar-stream@0.4.7 
        │ │ │ │   ├─┬ bl@0.9.4 
        │ │ │ │   │ └── readable-stream@1.0.33 
        │ │ │ │   └── end-of-stream@1.1.0 
        │ │ │ ├─┬ decompress-tarbz2@2.0.2 
        │ │ │ │ ├── is-bzip2@1.0.0 
        │ │ │ │ └─┬ seek-bzip@1.0.5 
        │ │ │ │   └─┬ commander@2.8.1 
        │ │ │ │     └── graceful-readlink@1.0.1 
        │ │ │ ├─┬ decompress-targz@2.1.0 
        │ │ │ │ ├── is-gzip@1.0.0 
        │ │ │ │ ├─┬ strip-dirs@1.1.1 
        │ │ │ │ │ ├─┬ chalk@1.1.1 
        │ │ │ │ │ │ ├── ansi-styles@2.1.0 
        │ │ │ │ │ │ ├─┬ has-ansi@2.0.0 
        │ │ │ │ │ │ │ └── ansi-regex@2.0.0 
        │ │ │ │ │ │ ├── strip-ansi@3.0.0 
        │ │ │ │ │ │ └── supports-color@2.0.0 
        │ │ │ │ │ ├── get-stdin@4.0.1 
        │ │ │ │ │ ├── is-natural-number@2.0.0 
        │ │ │ │ │ └─┬ sum-up@1.0.2 
        │ │ │ │ │   └─┬ chalk@1.1.1 
        │ │ │ │ │     ├── ansi-styles@2.1.0 
        │ │ │ │ │     ├─┬ has-ansi@2.0.0 
        │ │ │ │ │     │ └── ansi-regex@2.0.0 
        │ │ │ │ │     ├── strip-ansi@3.0.0 
        │ │ │ │ │     └── supports-color@2.0.0 
        │ │ │ │ └─┬ tar-stream@1.2.1 
        │ │ │ │   ├── bl@1.0.0 
        │ │ │ │   └── readable-stream@2.0.2 
        │ │ │ ├─┬ decompress-unzip@2.1.2 
        │ │ │ │ ├── is-zip@1.0.0 
        │ │ │ │ ├─┬ strip-dirs@1.1.1 
        │ │ │ │ │ ├─┬ chalk@1.1.1 
        │ │ │ │ │ │ ├── ansi-styles@2.1.0 
        │ │ │ │ │ │ ├─┬ has-ansi@2.0.0 
        │ │ │ │ │ │ │ └── ansi-regex@2.0.0 
        │ │ │ │ │ │ ├── strip-ansi@3.0.0 
        │ │ │ │ │ │ └── supports-color@2.0.0 
        │ │ │ │ │ └── get-stdin@4.0.1 
        │ │ │ │ └─┬ yauzl@2.3.1 
        │ │ │ │   ├── fd-slicer@1.0.1 
        │ │ │ │   └── pend@1.2.0 
        │ │ │ ├─┬ download-status@2.2.1 
        │ │ │ │ ├─┬ lpad-align@1.1.0 
        │ │ │ │ │ ├── get-stdin@4.0.1 
        │ │ │ │ │ ├── longest@1.0.1 
        │ │ │ │ │ └── lpad@2.0.1 
        │ │ │ │ ├── object-assign@2.1.1 
        │ │ │ │ └── progress@1.1.8 
        │ │ │ ├─┬ each-async@1.1.1 
        │ │ │ │ ├── onetime@1.0.0 
        │ │ │ │ └── set-immediate-shim@1.0.1 
        │ │ │ ├── get-stdin@3.0.2 
        │ │ │ ├── gulp-rename@1.2.2 
        │ │ │ ├─┬ meow@2.1.0 
        │ │ │ │ ├─┬ indent-string@1.2.2 
        │ │ │ │ │ ├── get-stdin@4.0.1 
        │ │ │ │ │ └── repeating@1.1.3 
        │ │ │ │ └── object-assign@2.1.1 
        │ │ │ ├─┬ rc@0.5.5 
        │ │ │ │ ├── deep-extend@0.2.11 
        │ │ │ │ ├── ini@1.3.4 
        │ │ │ │ ├── minimist@0.0.10 
        │ │ │ │ └── strip-json-comments@0.1.3 
        │ │ │ ├─┬ request@2.64.0 
        │ │ │ │ ├── aws-sign2@0.5.0 
        │ │ │ │ ├─┬ bl@1.0.0 
        │ │ │ │ │ └── readable-stream@2.0.2 
        │ │ │ │ ├── caseless@0.11.0 
        │ │ │ │ ├─┬ combined-stream@1.0.5 
        │ │ │ │ │ └── delayed-stream@1.0.0 
        │ │ │ │ ├── extend@3.0.0 
        │ │ │ │ ├── forever-agent@0.6.1 
        │ │ │ │ ├─┬ form-data@1.0.0-rc3 
        │ │ │ │ │ └── async@1.4.2 
        │ │ │ │ ├─┬ har-validator@1.8.0 
        │ │ │ │ │ ├── bluebird@2.10.2 
        │ │ │ │ │ ├─┬ chalk@1.1.1 
        │ │ │ │ │ │ ├── ansi-styles@2.1.0 
        │ │ │ │ │ │ ├─┬ has-ansi@2.0.0 
        │ │ │ │ │ │ │ └── ansi-regex@2.0.0 
        │ │ │ │ │ │ ├── strip-ansi@3.0.0 
        │ │ │ │ │ │ └── supports-color@2.0.0 
        │ │ │ │ │ └─┬ is-my-json-valid@2.12.2 
        │ │ │ │ │   ├── generate-function@2.0.0 
        │ │ │ │ │   ├─┬ generate-object-property@1.2.0 
        │ │ │ │ │   │ └── is-property@1.0.2 
        │ │ │ │ │   └── jsonpointer@2.0.0 
        │ │ │ │ ├─┬ hawk@3.1.0 
        │ │ │ │ │ ├── boom@2.9.0 
        │ │ │ │ │ ├── cryptiles@2.0.5 
        │ │ │ │ │ ├── hoek@2.16.3 
        │ │ │ │ │ └── sntp@1.0.9 
        │ │ │ │ ├─┬ http-signature@0.11.0 
        │ │ │ │ │ ├── asn1@0.1.11 
        │ │ │ │ │ ├── assert-plus@0.1.5 
        │ │ │ │ │ └── ctype@0.5.3 
        │ │ │ │ ├── isstream@0.1.2 
        │ │ │ │ ├── json-stringify-safe@5.0.1 
        │ │ │ │ ├─┬ mime-types@2.1.7 
        │ │ │ │ │ └── mime-db@1.19.0 
        │ │ │ │ ├── node-uuid@1.4.3 
        │ │ │ │ ├── oauth-sign@0.8.0 
        │ │ │ │ ├── qs@5.1.0 
        │ │ │ │ ├── stringstream@0.0.4 
        │ │ │ │ ├── tough-cookie@2.2.0 
        │ │ │ │ └── tunnel-agent@0.4.1 
        │ │ │ ├─┬ stream-combiner@0.2.2 
        │ │ │ │ └── duplexer@0.1.1 
        │ │ │ ├─┬ url-regex@2.1.3 
        │ │ │ │ └── ip-regex@1.0.3 
        │ │ │ ├─┬ vinyl@0.4.6 
        │ │ │ │ ├── clone@0.2.0 
        │ │ │ │ └── clone-stats@0.0.1 
        │ │ │ ├─┬ vinyl-fs@0.3.14 
        │ │ │ │ ├─┬ defaults@1.0.3 
        │ │ │ │ │ └── clone@1.0.2 
        │ │ │ │ ├─┬ glob-stream@3.1.18 
        │ │ │ │ │ ├── glob@4.5.3 
        │ │ │ │ │ ├─┬ glob2base@0.0.12 
        │ │ │ │ │ │ └── find-index@0.1.1 
        │ │ │ │ │ ├── minimatch@2.0.10 
        │ │ │ │ │ ├── ordered-read-streams@0.1.0 
        │ │ │ │ │ └── unique-stream@1.0.0 
        │ │ │ │ ├─┬ glob-watcher@0.0.6 
        │ │ │ │ │ └─┬ gaze@0.5.2 
        │ │ │ │ │   └─┬ globule@0.1.0 
        │ │ │ │ │     ├─┬ glob@3.1.21 
        │ │ │ │ │     │ ├── graceful-fs@1.2.3 
        │ │ │ │ │     │ └── inherits@1.0.2 
        │ │ │ │ │     ├── lodash@1.0.2 
        │ │ │ │ │     └─┬ minimatch@0.2.14 
        │ │ │ │ │       └── sigmund@1.0.1 
        │ │ │ │ ├── graceful-fs@3.0.8 
        │ │ │ │ └─┬ strip-bom@1.0.0 
        │ │ │ │   ├── first-chunk-stream@1.0.0 
        │ │ │ │   └── is-utf8@0.2.0 
        │ │ │ └─┬ ware@1.3.0 
        │ │ │   └─┬ wrap-fn@0.1.4 
        │ │ │     └── co@3.1.0 
        │ │ ├─┬ file-utils@0.2.2 
        │ │ │ ├── glob@4.5.3 
        │ │ │ ├── iconv-lite@0.4.13 
        │ │ │ ├── isbinaryfile@2.0.4 
        │ │ │ ├── lodash@2.4.2 
        │ │ │ └── minimatch@2.0.10 
        │ │ ├─┬ findup-sync@0.2.1 
        │ │ │ └─┬ glob@4.3.5 
        │ │ │   └── minimatch@2.0.10 
        │ │ ├─┬ github-username@1.1.1 
        │ │ │ ├── get-stdin@1.0.0 
        │ │ │ └─┬ got@2.9.2 
        │ │ │   ├─┬ duplexify@3.4.2 
        │ │ │   │ ├── end-of-stream@1.0.0 
        │ │ │   │ └── readable-stream@2.0.2 
        │ │ │   ├── infinity-agent@2.0.3 
        │ │ │   ├── is-stream@1.0.1 
        │ │ │   ├── lowercase-keys@1.0.0 
        │ │ │   ├── nested-error-stacks@1.0.1 
        │ │ │   ├── object-assign@2.1.1 
        │ │ │   ├── prepend-http@1.0.3 
        │ │ │   ├─┬ read-all-stream@2.2.0 
        │ │ │   │ └── readable-stream@2.0.2 
        │ │ │   ├── statuses@1.2.1 
        │ │ │   └── timed-out@2.0.0 
        │ │ ├─┬ glob@4.5.3 
        │ │ │ └── minimatch@2.0.10 
        │ │ ├─┬ gruntfile-editor@0.2.0 
        │ │ │ ├─┬ ast-query@0.2.5 
        │ │ │ │ ├─┬ escodegen@1.3.3 
        │ │ │ │ │ ├── esprima@1.1.1 
        │ │ │ │ │ ├── estraverse@1.5.1 
        │ │ │ │ │ ├── esutils@1.0.0 
        │ │ │ │ │ └─┬ source-map@0.1.43 
        │ │ │ │ │   └── amdefine@1.0.0 
        │ │ │ │ ├── esprima@1.1.1 
        │ │ │ │ ├── lodash@2.4.2 
        │ │ │ │ └── traverse@0.6.6 
        │ │ │ └── lodash@2.4.2 
        │ │ ├─┬ inquirer@0.8.5 
        │ │ │ ├── ansi-regex@1.1.1 
        │ │ │ ├─┬ chalk@1.1.1 
        │ │ │ │ ├── ansi-styles@2.1.0 
        │ │ │ │ ├─┬ has-ansi@2.0.0 
        │ │ │ │ │ └── ansi-regex@2.0.0 
        │ │ │ │ ├─┬ strip-ansi@3.0.0 
        │ │ │ │ │ └── ansi-regex@2.0.0 
        │ │ │ │ └── supports-color@2.0.0 
        │ │ │ ├── cli-width@1.0.1 
        │ │ │ ├── figures@1.4.0 
        │ │ │ ├─┬ readline2@0.1.1 
        │ │ │ │ ├── mute-stream@0.0.4 
        │ │ │ │ └─┬ strip-ansi@2.0.1 
        │ │ │ │   └── ansi-regex@1.1.1 
        │ │ │ ├── rx@2.5.3 
        │ │ │ └── through@2.3.8 
        │ │ ├─┬ istextorbinary@1.0.2 
        │ │ │ ├── binaryextensions@1.0.0 
        │ │ │ └── textextensions@1.0.1 
        │ │ ├── lodash@2.4.2 
        │ │ ├── mem-fs-editor@1.2.3 
        │ │ ├── mime@1.3.4 
        │ │ ├─┬ mkdirp@0.5.1 
        │ │ │ └── minimist@0.0.8 
        │ │ ├─┬ nopt@3.0.4 
        │ │ │ └── abbrev@1.0.7 
        │ │ ├─┬ pretty-bytes@1.0.4 
        │ │ │ └── get-stdin@4.0.1 
        │ │ ├── read-chunk@1.0.1 
        │ │ ├── run-async@0.1.0 
        │ │ ├── shelljs@0.3.0 
        │ │ ├─┬ sinon@1.17.1 
        │ │ │ ├── formatio@1.1.1 
        │ │ │ ├── lolex@1.3.2 
        │ │ │ ├── samsam@1.1.2 
        │ │ │ └── util@0.10.3 
        │ │ ├── text-table@0.2.0 
        │ │ ├─┬ through2@0.6.5 
        │ │ │ ├─┬ readable-stream@1.0.33 
        │ │ │ │ ├── core-util-is@1.0.1 
        │ │ │ │ ├── isarray@0.0.1 
        │ │ │ │ └── string_decoder@0.10.31 
        │ │ │ └── xtend@4.0.0 
        │ │ ├── underscore.string@2.4.0 
        │ │ ├── user-home@1.1.1 
        │ │ ├── xdg-basedir@1.0.1 
        │ │ ├─┬ yeoman-assert@1.0.0 
        │ │ │ └── lodash@2.4.2 
        │ │ ├─┬ yeoman-environment@1.2.7 
        │ │ │ ├─┬ chalk@1.1.1 
        │ │ │ │ ├── ansi-styles@2.1.0 
        │ │ │ │ ├─┬ has-ansi@2.0.0 
        │ │ │ │ │ └── ansi-regex@2.0.0 
        │ │ │ │ ├── strip-ansi@3.0.0 
        │ │ │ │ └── supports-color@2.0.0 
        │ │ │ ├─┬ globby@2.1.0 
        │ │ │ │ ├─┬ array-union@1.0.1 
        │ │ │ │ │ └── array-uniq@1.0.2 
        │ │ │ │ ├── async@1.4.2 
        │ │ │ │ └── object-assign@3.0.0 
        │ │ │ ├─┬ grouped-queue@0.3.0 
        │ │ │ │ ├── lodash@2.4.2 
        │ │ │ │ └── setimmediate@1.0.2 
        │ │ │ ├─┬ log-symbols@1.0.2 
        │ │ │ │ └─┬ chalk@1.1.1 
        npm WARN EPEERINVALID generator-joli-symfony@1.0.0 requires a peer of yo@>=1.0.0 but none was installed.

        │ │ │ │   ├─┬ has-ansi@2.0.0 
        │ │ │ │   │ └── ansi-regex@2.0.0 
        │ │ │ │   ├── strip-ansi@3.0.0 
        │ │ │ │   └── supports-color@2.0.0 
        │ │ │ ├─┬ mem-fs@1.1.0 
        │ │ │ │ └─┬ vinyl-file@1.2.1 
        │ │ │ │   ├── strip-bom@2.0.0 
        │ │ │ │   ├── strip-bom-stream@1.0.0 
        │ │ │ │   └─┬ vinyl@0.5.3 
        │ │ │ │     ├── clone@1.0.2 
        │ │ │ │     └── replace-ext@0.0.1 
        │ │ │ └─┬ untildify@2.1.0 
        │ │ │   └── os-homedir@1.0.1 
        │ │ └─┬ yeoman-welcome@1.0.1 
        │ │   └─┬ chalk@1.1.1 
        │ │     ├── ansi-styles@2.1.0 
        │ │     ├─┬ has-ansi@2.0.0 
        │ │     │ └── ansi-regex@2.0.0 
        │ │     ├── strip-ansi@3.0.0 
        │ │     └── supports-color@2.0.0 
        │ └─┬ yosay@0.3.0 
        │   ├── ansi-regex@0.2.1 
        │   ├─┬ chalk@0.4.0 
        │   │ ├── ansi-styles@1.0.0 
        │   │ ├── has-color@0.1.7 
        │   │ └── strip-ansi@0.1.1 
        │   ├── minimist@0.2.0 
        │   ├── pad-component@0.0.1 
        │   ├─┬ string-length@0.1.2 
        │   │ └─┬ strip-ansi@0.2.2 
        │   │   └── ansi-regex@0.1.0 
        │   ├─┬ strip-ansi@0.2.2 
        │   │ └── ansi-regex@0.1.0 
        │   ├─┬ taketalk@0.1.1 
        │   │ ├── get-stdin@0.1.0 
        │   │ └── minimist@0.1.0 
        │   └── word-wrap@0.1.3 
        └── UNMET PEER DEPENDENCY yo@>=1.0.0

**Comment by davidlemaitre** [comment]
I met the same issue
node 4.2.2
npm 3.4.0
yo 1.5.0
