### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by kix** [jolicode/generator-joli-symfony#9]
Installation fails on Node v0.10.26 & npm 1.4.3, Mac OS X 10.9.5:

```
npm ERR! peerinvalid The package generator-mocha does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-backbone@0.2.3 wants generator-mocha@>=0.1.1
npm ERR! peerinvalid Peer generator-bootstrap-less@3.2.1 wants generator-mocha@~0.1.6

npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/local/Cellar/node/0.10.26/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-joli-symfony"
npm ERR! cwd /Users/kix
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code EPEERINVALID
```

Here's a Gist with the log: https://gist.github.com/kix/0d075cda5be86cf21dda

**Comment by lbrunet** [comment]
Hey kix,

I didn't manage to reproduce the error, but it seems that the problem come from mocha, it's a devdependices that I don't use, so I've removed it, let me know if it works for you

**Comment by kix** [comment]
@lbrunet, nope, still fails :(

**Comment by lbrunet** [comment]
Hi Kix, 

can you give me your module list installed globally ? You can retrieve this list with : `npm list -g`

**Comment by kix** [comment]
@lbrunet, got it resolved by uninstalling generator-mocha, it produced the peerInvalid error. Thanks!

**Comment by kix** [comment]
Here's the global module list: https://gist.github.com/kix/42ff66961850f38186c9
